# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: front CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
#     - name: cd dir
#       run: cd frontend
#     - name: test cd
#       run: cd --help
#     - name: show path
#       run:  pwd
#     - name: cd to higher
#       run:  cd ../
    - name: show path
      run:  pwd
#     - name: show files
#       run: ls -a -1
#     - name: cd dir
#       run: cd ./frontend
    - name: show path
      run:  pwd
      working-directory: ./frontend
    - name: show files
      run: ls -a -1
    - name: show files
      run: ls -a -1
      working-directory: ./frontend
      
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      run: |
        npm install
        npm run build
      working-directory: ./frontend
